import SearchForm from "../../components/search/SearchForm";
import Item from "../../components/items/Item";
import Head from 'next/head';

const IdItem = () => {
    return (
        <div>
            <Head>
                <title>Detalle del producto</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section>
                <SearchForm />
                <Item />
            </section>
        </div>
    );
}
 
export default IdItem;