import Head from 'next/head';
import SearchForm from '../components/search/SearchForm';
import styles from '../styles/Search.module.scss';

const SearchBox = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fake MercadoLibre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section style={styles.main}>
        <SearchForm />
      </section>
    </div>
  )
}

export default SearchBox;