import Head from 'next/head';
import SearchForm from '../components/search/SearchForm';
import styles from '../styles/Search.module.scss';
import Image from 'next/image';
import Architecture from '../public/MeliTest.jpeg';
import { SiVercel, SiHeroku, SiGithub } from 'react-icons/si'


const SearchBox = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>TestMeli app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <SearchForm />
      </section>
      <section className={styles.docu}>
        <h2>Arquitectura TestMeli App</h2>
        <div className={styles.arq}>
          <Image src={Architecture} />
        </div>
        <h3>Servicios y Repositorios</h3> 
        <ul>
          <li>
            Backend: <SiHeroku /> Heroku | 
            Repo: <a href='https://github.com/Oscartic/api-meli' target='new'><SiGithub /> Github</a>
          </li>
          <li>
            Frontend: <SiVercel /> Vercel (front-meli-eight.vercel.app) |
            Repo: <a  href='https://github.com/Oscartic/front-meli' target='new'><SiGithub /> Github</a>
          </li>
          
        </ul>
      </section>
    </div>
  )
}

export default SearchBox;