import Head from 'next/head';
import ItemsList from '../components/items/ItemsList';
import SearchForm from '../components/search/SearchForm';

const Items = () => {

    return (
        <div>
            <Head>
                <title>Fake MercadoLibre</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section>
                <SearchForm />
                <ItemsList />
            </section>
        </div>
    );
}

export default Items;